#!/usr/bin/env bash

commit_msg="$1"
commit_type="$2"
commit_sha1="$3" # only present when amending a commit

# Leave merge commits (commit_type=merge), etc. through unchanged.
if [[ "$commit_type" != "message" ]]; then
  exit 0
fi

echo testing >> "$commit_msg"

sed -i 's/apple/orange/g' "$commit_msg"
