#!/usr/bin/env bash

commit_msg_file="$1"
commit_type="$2"
commit_sha1="$3" # only present when amending a commit

# Leave merge commits (commit_type=merge), etc. through unchanged.
if [[ "$commit_type" != "message" ]]; then
  exit 0
fi

branch=$(git rev-parse --symbolic --abbrev-ref HEAD)

echo "Committing into branch: $branch" > $commit_msg_file;
echo "" >> $commit_msg_file;
echo "Some initial commit message body." >> $commit_msg_file;

