#!/usr/bin/env bash

set -e

echo "Installing hooks..."

# Reference:
# https://www.viget.com/articles/two-ways-to-share-git-hooks-with-your-team/
find .git/hooks -type l -exec rm {} \; \
  && find .githooks -type f -exec ln -sf ../../{} .git/hooks/ \;

echo "Done."
